version: '3.1'
services:
  stats-service:
    build: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - STATS_SERVICE_URL=http://stats:9090

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=postgres-stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
